Repository west-eastH/SWUNIV-2024, pull requests merged in 2024-10, with the labels that each got.

#6 Feat/#WD-9: 랜딩 페이지 퍼블리싱
  app/package.json
  app/pnpm-lock.yaml
  app/public/fonts/Pretendard-Black.woff2
  app/public/fonts/Pretendard-Bold.woff2
  app/public/fonts/Pretendard-ExtraBold.woff2
  app/public/fonts/Pretendard-ExtraLight.woff2
  app/public/fonts/Pretendard-Light.woff2
  app/public/fonts/Pretendard-Medium.woff2
  app/public/fonts/Pretendard-Regular.woff2
  app/public/fonts/Pretendard-SemiBold.woff2
  app/public/fonts/Pretendard-Thin.woff2
  app/public/images/hbu_character_logo.png
  app/src/App.tsx
  app/src/app/config/index.ts
  app/src/app/config/router/RouterProvider.tsx
  app/src/app/config/router/consts/path.ts
  app/src/app/config/router/index.tsx
  app/src/app/config/router/router.tsx
  app/src/app/config/style/global.css
  app/src/assets/react.svg
  app/src/features/typing-rotate/index.tsx
  app/src/index.css
  app/src/main.tsx
  app/src/pages/landing/index.tsx
  app/src/pages/landing/ui/ControlSection.tsx
  app/src/pages/landing/ui/Layout.tsx
  app/src/pages/landing/ui/Logo.tsx
  app/src/pages/landing/ui/TitleSection.tsx
  app/src/pages/landing/ui/page.tsx
  app/src/shared/style/consts/palette.ts
  app/src/shared/style/index.tsx
  app/src/shared/ui/app-layout/ParentLayer.tsx
  app/src/shared/ui/app-layout/UILayer.tsx
  app/src/shared/ui/app-layout/index.tsx
  app/src/shared/ui/button/index.tsx
  app/src/shared/ui/index.tsx
  app/src/shared/ui/typo/index.tsx
  app/tailwind.config.js
  app/tsconfig.app.json
  app/vite.config.ts
Labels: 🌟 DESIGN

#7 Feat/#WD-42: IP 필터링
  .gitignore
  hanbatbox-api/.gitignore
  hanbatbox-api/build.gradle
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/config/SecurityConfig.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/TestController.java
  hanbatbox-api/src/main/resources/application.yml
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/TestControllerTest.java
Labels: 🌳 FEATURE

#10 Feat/WD-36: 닉네임 자동 발급 모듈
  app/.babelrc
  app/jest.config.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/features/nickname/consts/parts.ts
  app/src/features/nickname/generator.ts
  app/src/features/nickname/index.ts
  app/src/features/nickname/lib/selectRand.ts
  app/src/pages/landing/ui/Layout.tsx
  app/src/pages/landing/ui/TitleSection.tsx
  app/src/test/generate-name.test.ts
  app/tsconfig.app.json
  app/tsconfig.node.json
  github/PULL_REQUEST_TEMPLATE.md
Labels: 🌳 FEATURE

#9 feat/WD-31: 파일 업로드 api 구현
  app/package-lock.json
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/S3/S3Config.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/S3/controller/S3Controller.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/S3/service/S3Service.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/S3Config.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/exception/GlobalExceptionHandler.java
  hanbatbox-api/src/main/resources/application.yml
  hanbatbox-api/src/main/resources/code_style/intellij-java-google-style.xml
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/S3/controller/S3ControllerTest.java
Labels: 🌳 FEATURE

#11 feat/WD-31
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/S3/service/S3Service.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/config/S3Config.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/S3Controller.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/entitiy/S3Service.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/exception/GlobalExceptionHandler.java
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/S3/controller/S3ControllerTest.java
Labels: 🐛 FIX

#12 Feat/WD-45: 도메인 생성 & 기본적인 레포지토리 생성
  hanbatbox-api/Makefile
  hanbatbox-api/build.gradle
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/HanbatboxApplication.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/config/SecurityConfig.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/TestController.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/domain/Box.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/domain/Item.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/repository/BoxRepository.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/repository/ItemRepository.java
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/HanbatboxApplicationTests.java
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/controller/TestControllerTest.java
Labels: 🌳 FEATURE

#13 Feat/#WD-46: 모바일 레이아웃 기능 작성
  app/src/app/config/router/consts/path.ts
  app/src/app/config/router/index.tsx
  app/src/app/config/router/router.tsx
  app/src/app/config/style/global.css
  app/src/features/layout/GNB/Button.tsx
  app/src/features/layout/GNB/index.tsx
  app/src/features/layout/Header/index.tsx
  app/src/features/layout/Mobile.tsx
  app/src/features/layout/index.tsx
  app/src/pages/home/index.tsx
  app/src/pages/home/ui/page.tsx
  app/src/shared/assets/icon/header-logo.svg
  app/src/shared/assets/icon/home_active.svg
  app/src/shared/assets/icon/home_deactive.svg
  app/src/shared/assets/icon/menu_active.svg
  app/src/shared/assets/icon/menu_deactive.svg
  app/src/shared/assets/icon/upload_active.svg
  app/src/shared/assets/icon/upload_deactive.svg
  app/src/shared/ui/app-layout/ParentLayer.tsx
  app/src/shared/ui/app-layout/UILayer.tsx
  app/src/shared/ui/icon/index.tsx
  app/src/shared/ui/index.tsx
  app/vite.config.ts
Labels: 🌟 DESIGN, 🌳 FEATURE

#14 Feat/#WD-47: 사용자 닉네임 기반 로그인, 로그아웃
  app/src/app/config/router/router.tsx
  app/src/features/nickname/generator/consts/parts.ts
  app/src/features/nickname/generator/index.ts
  app/src/features/nickname/generator/lib/selectRand.ts
  app/src/features/nickname/index.ts
  app/src/features/nickname/indicator/index.tsx
  app/src/features/nickname/indicator/lib/useNameManager.tsx
  app/src/pages/home/ui/page.tsx
  app/src/pages/landing/index.tsx
  app/src/pages/landing/ui/ControlSection.tsx
  app/src/pages/landing/ui/MainRouter.tsx
  app/src/shared/assets/icon/upload-white.svg
  app/src/shared/ui/button/index.tsx
  app/src/shared/ui/icon/index.tsx
  app/src/widgets/dashboard-panel/index.tsx
Labels: 🌟 DESIGN, 🌳 FEATURE

#19 Feat/#WD-27: 한밭대 지역권 여부 API
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/IpCheckController.java
Labels: 🌳 FEATURE

#16 [feat]: file download api 구현 및 파일사이즈와 타이틀 가져오기 구현, 테스트 코드 어노테이션 수정
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/S3Controller.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/service/S3Service.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/service/TempFileService.java
  hanbatbox-api/src/test/java/com/hbu/hanbatbox/controller/S3ControllerTest.java
Labels: 🌳 FEATURE, 💐 REFACTOR

#26 Fix/#WD-50: 기아 쓰레드 에러 수정
  hanbatbox-api/src/main/resources/application.yml
Labels: 🐛 FIX

#28 Feat/#WD-18: 홈화면 파일 리스트 불러오기
  app/src/features/ScrollEndObserver/index.tsx
  app/src/features/upload-box/api/index.ts
  app/src/features/upload-box/api/useBoxesQuery.tsx
  app/src/features/upload-box/ui/list/index.tsx
  app/src/features/upload-box/ui/search/index.tsx
  app/src/pages/home/ui/page.tsx
  app/src/pages/upload/ui/page.tsx
  app/src/shared/ui/dropdown/index.tsx
  app/src/widgets/nickname-changer/index.tsx
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/repository/BoxRepository.java
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/service/BoxService.java
Labels: 🌳 FEATURE

#29 Feat/#WD-52: 모달 개선 및 로딩 기능 추가
  app/package.json
  app/pnpm-lock.yaml
  app/src/features/upload-box/api/useBoxesQuery.tsx
  app/src/pages/upload/ui/page.tsx
  app/src/shared/config/axios/index.ts
  app/src/shared/ui/modal/config/ModalProvider.tsx
  app/src/shared/ui/modal/types/index.ts
  app/src/widgets/modal/index.tsx
  app/src/widgets/modal/useLoading.tsx
  app/src/widgets/nickname-changer/index.tsx
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/repository/BoxRepository.java
Labels: 🌳 FEATURE, 💐 REFACTOR

#31 [feat]: delete 메서드 구현
  hanbatbox-api/src/main/java/com/hbu/hanbatbox/controller/S3Controller.java
Labels: 🌳 FEATURE
